#!/usr/bin/env node
/**
 * Campaign analysis: percentile-based latency characterization.
 *
 * Reads evaluation-results.json (forward direction) and, if present,
 * reverse-results.json. Produces:
 *   - console report: n, distinct days, per-leg and end-to-end
 *     mean/std/min/p50/p90/p95/p99/max
 *   - latency-cdf.csv        (end-to-end CDF points, for pgfplots)
 *   - latency-summary.tex    (LaTeX-ready sentence + table rows with the
 *                             measured numbers, to paste into Section VI-A)
 *
 * Usage: node scripts/campaign-analyze.js
 */
const path = require('path');
const fs = require('fs');

const RESULTS = path.join(__dirname, 'evaluation-results.json');
const REVERSE = path.join(__dirname, 'reverse-results.json');

function pct(sorted, p) {
    if (sorted.length === 0) return NaN;
    const idx = Math.min(sorted.length - 1, Math.ceil((p / 100) * sorted.length) - 1);
    return sorted[Math.max(0, idx)];
}

function stats(values) {
    const v = values.filter((x) => Number.isFinite(x)).sort((a, b) => a - b);
    const n = v.length;
    if (n === 0) return null;
    const mean = v.reduce((s, x) => s + x, 0) / n;
    const std = Math.sqrt(v.reduce((s, x) => s + (x - mean) ** 2, 0) / (n > 1 ? n - 1 : 1));
    return {
        n, mean, std, min: v[0], max: v[n - 1],
        p50: pct(v, 50), p90: pct(v, 90), p95: pct(v, 95), p99: pct(v, 99),
        sorted: v,
    };
}

const fmt = (x, d = 1) => (Number.isFinite(x) ? x.toFixed(d) : 'n/a');

function report(name, s) {
    if (!s) { console.log(`  ${name}: no data`); return; }
    console.log(`  ${name.padEnd(22)} n=${s.n}  mean=${fmt(s.mean)}s std=${fmt(s.std)}  ` +
        `min=${fmt(s.min)} p50=${fmt(s.p50)} p90=${fmt(s.p90)} p95=${fmt(s.p95)} p99=${fmt(s.p99)} max=${fmt(s.max)}`);
}

function main() {
    if (!fs.existsSync(RESULTS)) { console.error('No evaluation-results.json found.'); process.exit(1); }
    const data = JSON.parse(fs.readFileSync(RESULTS, 'utf8'));
    const runs = (data.runs || []).filter((r) => r.success);
    const failed = (data.runs || []).length - runs.length;

    const days = new Set(runs.map((r) => new Date((r.lock?.timestamp || 0) * 1000).toISOString().slice(0, 10)));
    const hours = new Set(runs.map((r) => new Date((r.lock?.timestamp || 0) * 1000).getUTCHours()));

    const e2e = stats(runs.map((r) => r.totalTimeSeconds));
    const fwd = stats(runs.map((r) => r.relay?.relayLatencySeconds));
    const cb = stats(runs.map((r) =>
        r.burn?.callbackLatencySeconds ??
        ((r.burn && r.claim) ? r.burn.timestamp - r.claim.timestamp : NaN)));
    const autoCount = runs.filter((r) => r.burn?.mode === 'automatic-callback').length;
    const manualCount = runs.filter((r) => r.burn?.mode === 'manual-fallback').length;
    const lockGas = stats(runs.map((r) => r.lock?.gasUsed));
    const burnGas = stats(runs.map((r) => r.burn?.gasUsed));
    const claimGas = stats(runs.map((r) => r.claim?.gasUsed));

    console.log('==== Forward direction (Polygon -> Neutron) ====');
    console.log(`  successful runs: ${runs.length} (failed/incomplete: ${failed})`);
    console.log(`  coverage: ${days.size} distinct day(s), ${hours.size} distinct UTC hour(s): [${[...hours].sort((a, b) => a - b).join(', ')}]`);
    if (autoCount + manualCount > 0) {
        console.log(`  burn path: ${autoCount} automatic-callback, ${manualCount} manual-fallback (monitor)`);
    }
    report('end-to-end (s)', e2e);
    report('forward relay (s)', fwd);
    report('callback/burn leg (s)', cb);
    report('lockForBurn gas', lockGas);
    report('claim_mint gas', claimGas);
    report('burn gas', burnGas);

    if (e2e) {
        // CDF for pgfplots: x = seconds, y = fraction of runs <= x
        const lines = ['latency_s,cdf'];
        e2e.sorted.forEach((x, i) => lines.push(`${x},${((i + 1) / e2e.n).toFixed(4)}`));
        fs.writeFileSync(path.join(__dirname, 'latency-cdf.csv'), lines.join('\n'));
        console.log('\nWrote latency-cdf.csv');

        const tex = [
            '% Auto-generated by campaign-analyze.js -- paste/adapt into Section VI-A.',
            `% n=${e2e.n}, days=${days.size}, generated ${new Date().toISOString()}`,
            `We executed ${e2e.n} end-to-end transfers from Polygon to Neutron across`,
            `${days.size} distinct days (${hours.size} distinct UTC hours). All succeeded.`,
            `Median end-to-end latency was ${fmt(e2e.p50, 0)}~s (p90 ${fmt(e2e.p90, 0)}~s, p95 ${fmt(e2e.p95, 0)}~s,`,
            `p99 ${fmt(e2e.p99, 0)}~s, max ${fmt(e2e.max, 0)}~s), decomposed as ${fmt(fwd?.p50 ?? NaN, 0)}~s median forward relay`,
            `and ${fmt(cb?.p50 ?? NaN, 0)}~s median callback leg.`,
        ];
        fs.writeFileSync(path.join(__dirname, 'latency-summary.tex'), tex.join('\n') + '\n');
        console.log('Wrote latency-summary.tex');
    }

    if (fs.existsSync(REVERSE)) {
        const rev = JSON.parse(fs.readFileSync(REVERSE, 'utf8'));
        const ok = rev.filter((r) => r.legs?.burn && r.legs.burn.mode !== 'callback-pending');
        console.log('\n==== Reverse direction (Neutron -> Polygon) ====');
        console.log(`  completed runs: ${ok.length} of ${rev.length}`);
        report('end-to-end (s)', stats(ok.map((r) => r.endToEndSeconds)));
        report('forward relay (s)', stats(ok.map((r) => r.legs?.forwardRelaySeconds)));
        report('callback leg (s)', stats(ok.map((r) => r.legs?.callbackRelaySeconds)));
    } else {
        console.log('\n(no reverse-results.json yet — run scripts/htlc-reverse-test.js)');
    }
}

main();
